---
# golangci-lint configuration for backend
run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Static analysis checks
    - unused        # Checks for unused code
    - gofmt         # Check code formatting
    - misspell      # Check for misspellings
    - revive        # Drop-in replacement for golint

linters-settings:
  errcheck:
    check-blank: false
    check-type-assertions: false
  govet:
    check-shadowing: false
  revive:
    confidence: 0.8

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
