version: "1"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - typecheck
    - gofmt
    - misspell
    - revive
    - gosec
    - gocritic
    - stylecheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
