global:
    scrape_interval: 15s

scrape_configs:
    - job_name: 'go_app'
      static_configs:
          - targets: ['go_app:8000']
    - job_name: 'prometheus'
      static_configs:
        - targets: ['prometheus:9090']

