export { default as About } from './About'
export { default as Home } from './Home'
export { default as ProjectDetail } from './ProjectDetail'
export { default as Projects } from './Projects'
export { default as Support } from './Support'
