// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Event struct {
	ID        int32           `json:"id"`
	EventName sql.NullString  `json:"event_name"`
	Data      json.RawMessage `json:"data"`
	Referrer  sql.NullString  `json:"referrer"`
	UserAgent sql.NullString  `json:"user_agent"`
	SessionID sql.NullString  `json:"session_id"`
	IpAddress sql.NullString  `json:"ip_address"`
	ViewedAt  time.Time       `json:"viewed_at"`
	UserID    sql.NullInt32   `json:"user_id"`
}

type Log struct {
	ID        int32           `json:"id"`
	Level     string          `json:"level"`
	Message   string          `json:"message"`
	Context   json.RawMessage `json:"context"`
	IpAddress sql.NullString  `json:"ip_address"`
	CreatedAt time.Time       `json:"created_at"`
}

type PageView struct {
	ID        int32          `json:"id"`
	Path      string         `json:"path"`
	Referrer  sql.NullString `json:"referrer"`
	UserAgent sql.NullString `json:"user_agent"`
	SessionID sql.NullString `json:"session_id"`
	IpAddress sql.NullString `json:"ip_address"`
	ViewedAt  time.Time      `json:"viewed_at"`
	UserID    sql.NullInt32  `json:"user_id"`
}

type Post struct {
	ID        int32          `json:"id"`
	Title     string         `json:"title"`
	Slug      string         `json:"slug"`
	Summary   sql.NullString `json:"summary"`
	Content   string         `json:"content"`
	Tags      []string       `json:"tags"`
	IsDraft   sql.NullBool   `json:"is_draft"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	UserID    sql.NullInt32  `json:"user_id"`
}

type Project struct {
	ID          int32          `json:"id"`
	Title       string         `json:"title"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	RepoUrl     sql.NullString `json:"repo_url"`
	LiveUrl     sql.NullString `json:"live_url"`
	Summary     sql.NullString `json:"summary"`
	Tags        []string       `json:"tags"`
	Footer      sql.NullString `json:"footer"`
	Href        sql.NullString `json:"href"`
	External    bool           `json:"external"`
	Color       sql.NullString `json:"color"`
	Emoji       sql.NullString `json:"emoji"`
	Content     sql.NullString `json:"content"`
	Image       sql.NullString `json:"image"`
	Embed       sql.NullString `json:"embed"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	UserID      sql.NullInt32  `json:"user_id"`
}

type Session struct {
	ID        uuid.UUID      `json:"id"`
	UserID    sql.NullInt32  `json:"user_id"`
	IpAddress sql.NullString `json:"ip_address"`
	UserAgent sql.NullString `json:"user_agent"`
	CreatedAt sql.NullTime   `json:"created_at"`
	ExpiresAt sql.NullTime   `json:"expires_at"`
}

type User struct {
	ID           int32          `json:"id"`
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}
