// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Event struct {
	ID         int32                 `json:"id"`
	EventName  sql.NullString        `json:"event_name"`
	Data       pqtype.NullRawMessage `json:"data"`
	SessionID  sql.NullString        `json:"session_id"`
	IpAddress  sql.NullString        `json:"ip_address"`
	OccurredAt time.Time             `json:"occurred_at"`
}

type Log struct {
	ID        int32                 `json:"id"`
	Level     string                `json:"level"`
	Message   string                `json:"message"`
	Context   pqtype.NullRawMessage `json:"context"`
	IpAddress sql.NullString        `json:"ip_address"`
	CreatedAt time.Time             `json:"created_at"`
}

type PageView struct {
	ID        int32          `json:"id"`
	Path      string         `json:"path"`
	Referrer  sql.NullString `json:"referrer"`
	UserAgent sql.NullString `json:"user_agent"`
	SessionID sql.NullString `json:"session_id"`
	IpAddress sql.NullString `json:"ip_address"`
	ViewedAt  time.Time      `json:"viewed_at"`
}

type Post struct {
	ID          int32          `json:"id"`
	Title       string         `json:"title"`
	Slug        string         `json:"slug"`
	Summary     sql.NullString `json:"summary"`
	Content     string         `json:"content"`
	PublishedAt time.Time      `json:"published_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	Tags        []string       `json:"tags"`
	IsDraft     sql.NullBool   `json:"is_draft"`
}

type Project struct {
	ID          int32          `json:"id"`
	Title       string         `json:"title"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	RepoUrl     sql.NullString `json:"repo_url"`
	LiveUrl     sql.NullString `json:"live_url"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID        int32        `json:"id"`
	Username  string       `json:"username"`
	Email     string       `json:"email"`
	CreatedAt sql.NullTime `json:"created_at"`
}
