// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CountEvents(ctx context.Context) (int64, error)
	CountViewsByPath(ctx context.Context, path string) (int64, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) error
	CreateLog(ctx context.Context, arg CreateLogParams) (Log, error)
	CreatePageView(ctx context.Context, arg CreatePageViewParams) error
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteLog(ctx context.Context, id int32) error
	DeletePost(ctx context.Context, id int32) error
	DeleteProject(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetEventsByName(ctx context.Context, arg GetEventsByNameParams) ([]Event, error)
	GetLogByID(ctx context.Context, id int32) (Log, error)
	GetPostBySlug(ctx context.Context, slug string) (Post, error)
	GetProjectBySlug(ctx context.Context, slug string) (Project, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetViewsByPath(ctx context.Context, arg GetViewsByPathParams) ([]PageView, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	ListLogs(ctx context.Context, arg ListLogsParams) ([]Log, error)
	ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
}

var _ Querier = (*Queries)(nil)
